// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5UuynoFwHVP-pkxlAVgUSzutZjJWJhFg',
    appId: '1:731094034670:web:d85b07e799462177136bff',
    messagingSenderId: '731094034670',
    projectId: 'geolocation-d39fd',
    authDomain: 'geolocation-d39fd.firebaseapp.com',
    storageBucket: 'geolocation-d39fd.firebasestorage.app',
    measurementId: 'G-SGR0LQNGZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8VUy_o3aVmP4zGBcZ_p1TWyzukChGiwc',
    appId: '1:731094034670:android:16bdc89a1c54ab1a136bff',
    messagingSenderId: '731094034670',
    projectId: 'geolocation-d39fd',
    storageBucket: 'geolocation-d39fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT13MpdwH-EFUEa1Gg79N0TkdJsqTEukQ',
    appId: '1:731094034670:ios:8b7bfaf71b66e503136bff',
    messagingSenderId: '731094034670',
    projectId: 'geolocation-d39fd',
    storageBucket: 'geolocation-d39fd.firebasestorage.app',
    iosBundleId: 'com.example.backlocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT13MpdwH-EFUEa1Gg79N0TkdJsqTEukQ',
    appId: '1:731094034670:ios:8b7bfaf71b66e503136bff',
    messagingSenderId: '731094034670',
    projectId: 'geolocation-d39fd',
    storageBucket: 'geolocation-d39fd.firebasestorage.app',
    iosBundleId: 'com.example.backlocation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5UuynoFwHVP-pkxlAVgUSzutZjJWJhFg',
    appId: '1:731094034670:web:a2a13019b09b0db9136bff',
    messagingSenderId: '731094034670',
    projectId: 'geolocation-d39fd',
    authDomain: 'geolocation-d39fd.firebaseapp.com',
    storageBucket: 'geolocation-d39fd.firebasestorage.app',
    measurementId: 'G-J2KTMG0S4T',
  );
}
